In [56]:
import numpy as np

# 数组创建与基本操作
a = np.array([[1, 2, 3], [4, 5, 6]])
print("形状:", a.shape)  # (2, 3)
print("维度:", a.ndim)   # 2

形状: (2, 3)
维度: 2


In [57]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
# 广播机制（Broadcasting）
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [60]:
result = a + b  # 自动扩展b的维度
print(result)

[[2 4 6]
 [5 7 9]]


In [61]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
# 广播机制（Broadcasting）
c = np.array([[1, 1, 1], [1, 1, 1]])
c

array([[1, 1, 1],
       [1, 1, 1]])

In [63]:
result = a + c
print(result)

[[2 3 4]
 [5 6 7]]


In [64]:
# 矩阵乘法
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A

array([[1, 2],
       [3, 4]])

In [65]:
B

array([[5, 6],
       [7, 8]])

In [66]:
C = np.dot(A, B)  # 或 A @ B
C

array([[19, 22],
       [43, 50]])

In [67]:
# 元素级运算
element_wise = A * B  # 对应元素相乘
element_wise

array([[ 5, 12],
       [21, 32]])

In [68]:
# 转置
A_T = A.T

In [8]:
A_T

array([[1, 3],
       [2, 4]])

In [9]:
# 求和操作
sum_all = np.sum(A)
sum_all

np.int64(10)

In [69]:
A

array([[1, 2],
       [3, 4]])

In [10]:
sum_axis0 = np.sum(A, axis=0)  # 按列求和
sum_axis0

array([4, 6])

In [71]:
sum_axis1 = np.sum(A, axis=1)
sum_axis1

array([3, 7])

In [11]:
sum_axis1 = np.sum(A, axis=1, keepdims=True)  # 按行求和，保持维度
sum_axis1

array([[3],
       [7]])

numpy.clip 是一个非常实用的函数，它的作用是 将数组中的元素限制在指定的区间范围内。超出范围的值会被截断到最小值或最大值。

应用场景

	1.	防止数值溢出或下溢（如梯度裁剪、图像处理）
	2.	限制信号范围（如 EEG/pupil 信号归一化）
	3.	图像像素值处理（将像素限制在 [0,255]）


In [73]:
import numpy as np

arr = np.array([1, 5, 70, 15, 20])

# 限制在区间 [5, 15]
clipped = np.clip(arr, 5, 18)
print(clipped)

[ 5  5 18 15 18]


数组创建

In [12]:
# 从列表/元组创建
arr = np.array([1, 2, 3])
arr2 = np.array([[1, 2], [3, 4]])

# 常用函数创建
zeros = np.zeros((2, 3))       # 全零数组
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
ones = np.ones((2, 3))         # 全一数组
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [75]:
full = np.full((2, 3), 1.5)      # 指定值数组
print(full)


[[1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [77]:
eye = np.eye(5)                 # 单位矩阵
print(eye)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
arange = np.arange(0, 10, 2)    # 类似 range
print(arange)

[0 2 4 6 8]


In [17]:
linspace = np.linspace(0, 1, 5) # 等间距
print(linspace)


[0.   0.25 0.5  0.75 1.  ]


In [79]:
random = np.random.rand(2,3)    # [0,1)均匀分布随机数
print(random)


[[0.59430535 0.38717225 0.60392166]
 [0.76146393 0.23319255 0.99411712]]


In [19]:
randn = np.random.randn(2,3)    # 标准正态分布随机数
print(randn)

[[-2.07240493  0.57642368 -0.01975042]
 [-0.97913866 -0.32015582  1.1140441 ]]


数组属性

```
arr.shape       # 形状
arr.ndim        # 维度
arr.size        # 元素总数
arr.dtype       # 数据类型
arr.itemsize    # 每个元素的字节大小
arr.data        # 数据缓冲区

```

In [21]:
A

array([[1, 2],
       [3, 4]])

In [20]:
A.shape       # 形状

(2, 2)

In [22]:
A.ndim        # 维度


2

In [23]:
A.size        # 元素总数

4

In [24]:
A.dtype       # 数据类型


dtype('int64')

In [25]:
A.itemsize    # 每个元素的字节大小


8

In [26]:
A.data        # 数据缓冲区


数组运算

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
b

array([1, 2, 3])

In [29]:
# 基本运算
a + b
a - b
a * b
a / b
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
# 矩阵乘法
a.dot(b)   # 或 np.dot(a,b)

array([14, 32])

In [32]:
a @ b      # Python 3.5+

array([14, 32])

In [33]:
# 广播机制示例
arr + 10   # 每个元素加 10

array([11, 12, 13])

索引与切片

In [80]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# 基本索引
arr[0,0]      # 第一行第一列

np.int64(1)

In [35]:
arr[1,:]      # 第二行

array([4, 5, 6])

In [36]:
arr[:,2]      # 第三列

array([3, 6, 9])

In [37]:
arr[-1,-1]    # 最后一个元素

np.int64(9)

In [81]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
# 布尔索引
arr[arr < 4]  

array([1, 2, 3])

In [90]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 花式索引
arr[[1,2,3],[0,1,2]] # arr[1,0]和arr[2,1]

array([4, 8])

常用函数

In [ ]:
# 数学函数
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [42]:
# 聚合函数
# np.cumsum(arr)   # 累加
# np.cumprod(arr)  # 累乘
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

45
5.0
2.581988897471611
1
9
0
8
[ 1  3  6 10 15 21 28 36 45]
[     1      2      6     24    120    720   5040  40320 362880]


In [92]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

	•	np.sort(arr) → 返回 排序后的数组。
	•	np.argsort(arr) → 返回 排序后的索引，即按照元素大小排序，原数组中元素对应的索引顺序。

In [94]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
# 排序
np.sort(arr)
np.argsort(arr)
print(np.sort(arr))
print(np.argsort(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [96]:
import numpy as np

arr = np.array([50, 10, 30, 20])

# 普通排序
sorted_arr = np.sort(arr)
print(sorted_arr)  
# 输出: [10 20 30 50]

# argsort
indices = np.argsort(arr)
print(indices)
# 输出: [1 3 2 0]

# 用 argsort 索引获取排序结果
print(arr[indices])
# 输出: [10 20 30 50]  → 和 np.sort(arr) 一样

[10 20 30 50]
[1 3 2 0]
[10 20 30 50]


In [97]:
arr

array([50, 10, 30, 20])

In [100]:
inx = np.array([1, 0, 2, 3])
inx

array([1, 0, 2, 3])

In [102]:
arr[0]

np.int64(50)

In [101]:
arr[inx]

array([10, 50, 30, 20])

线性代数

In [ ]:
# 矩阵运算
np.transpose(arr)   # 转置 arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
np.linalg.inv(arr)  # 逆矩阵

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [45]:
np.linalg.det(arr)  # 行列式

np.float64(-9.51619735392994e-16)

In [46]:
np.linalg.eig(arr)  # 特征值/特征向量

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -4.29954797e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))

np.linalg.solve 是 NumPy 中用来 解线性方程组 的函数。它的作用是求解 Ax = b 中的 x，其中 A 是系数矩阵，b 是常数向量（或矩阵）

In [ ]:
import numpy as np

# 系数矩阵 A
A = np.array([[2, 1],
              [3, 4]])

# 常数向量 b
b = np.array([5, 6])

# 求解 x
x = np.linalg.solve(A, b)
print(x)

[ 2.8 -0.6]


随机数

In [ ]:
np.random.seed(42)      # 固定随机种子
np.random.randint(1, 10, size=(2,3))  # 随机整数
np.random.rand(2,3)     # [0,1)均匀分布
np.random.randn(2,3)    # 标准正态分布
np.random.choice([1,2,3,4], size=3, replace=True)

其他常用操作

In [ ]:
# 数组形状操作
arr.reshape((3,2))
arr.flatten()
arr.ravel()
arr.T

# 拼接与分割
np.concatenate([a,b], axis=0)
np.vstack([a,b])
np.hstack([a,b])
np.split(arr, 2, axis=0)

In [ ]:
arr[arr > 9]

基础用法：条件选择元素

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# 找出大于3的元素索引
indices = np.where(arr > 3)
print(indices)          # 输出 (array([3, 4, 5]),)
print(arr[indices])     # 输出 [4 5 6]

# 直接用布尔条件
print(arr[arr > 3])     # 同上

(array([3, 4, 5]),)
[4 5 6]
[4 5 6]


用 where 做元素替换

In [105]:
arr = np.array([1, 2, 3, 4, 5, 6])

# 小于等于3的元素变成0，大于3的保持原值
new_arr = np.where(arr <= 2, 99, 88)
print(new_arr)  # 输出 [0 0 0 4 5 6]

[99 99 88 88 88 88]


In [104]:
arr

array([1, 2, 3, 4, 5, 6])

二维数组条件选择

多条件使用 where

In [ ]:
arr = np.array([10, 15, 20, 25, 30])

# 条件1：小于20 -> 0
# 条件2：大于等于20 -> 1
new_arr = np.where(arr < 20, 0, 1)
print(new_arr)  # 输出 [0 0 1 1 1]

# 可以嵌套 np.where 实现多条件
# 小于15 -> 0, 15~25 -> 1, 大于25 -> 2
new_arr2 = np.where(arr < 15, 0, np.where(arr <= 25, 1, 2)) # if arr < 15, elif arr <= 25 else
print(new_arr2)  # 输出 [0 1 1 1 2]

[0 0 1 1 1]
[0 1 1 1 2]


实际应用：选择两个数组的元素

In [53]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# 条件：a>3 选择 b，否则选择 a
result = np.where(a > 3, b, a)
print(result)  # 输出 [ 1  2  3 40 50]

[ 1  2  3 40 50]
